source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.0"

gem "rails", "~> 7.0.1"
gem "pg", "~> 1.1"
gem "puma", "~> 5.0"
gem "bootsnap", require: false
gem "rack-cors"
gem "application-base", path: "../engines/application-base"

group :development, :test do
  gem "factory_bot_rails"
  gem "ffaker"
  gem "pry-rails"
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-rspec", require: false
end

group :development do
  gem "spring"
  gem "letter_opener"
end

group :test do
  gem "rspec-rails"
  gem "shoulda-matchers"
  gem "simplecov"
end

